# Generated by Django 3.1 on 2020-09-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
    ]
