# Generated by Django 3.1 on 2020-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200911_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'FASHION'), ('Toys', 'TOYS'), ('Electronics', 'ELECTRONICS'), ('Home', 'HOME'), ('Sports', 'SPORTS')], default=None, max_length=11, null=True),
        ),
    ]
