# Generated by Django 3.1.1 on 2020-09-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200912_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
