# Generated by Django 3.1 on 2020-10-25 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201025_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
