# Generated by Django 3.1.2 on 2020-10-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='Test Message 20.10.30 01', max_length=2000),
            preserve_default=False,
        ),
    ]
