# Generated by Django 3.1.2 on 2020-12-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='writername',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
