# Generated by Django 3.1.3 on 2021-01-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201220_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='numoflikes',
            field=models.IntegerField(default=0),
        ),
    ]
